services:
  postgresql_server:
    container_name: ${COMPOSE_PROJECT_NAME}_postgresql_server
    image: ankane/pgvector:latest
    restart: always
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
      - ./config/pgvector_extension.sql:/docker-entrypoint-initdb.d/init-vector_extension.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    user: "0:0"   # 以root权限运行
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql_server

  redis_server:
    container_name: ${COMPOSE_PROJECT_NAME}_redis_server
    image: redis:alpine
    restart: always
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    volumes:
      - ./db/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --dir /data
